class HomeControllerBase:
    def __init__(self): ...
    def getHome(self): ...
    def getData(self): ...


class ProductControllerBase:
    def __init__(self): ...
    def getProducts(self): ...
    def getProductByUuid(self, uuid): ...
    def postProduct(self): ...
    def putProduct(self, uuid): ...
    def deleteProduct(self, uuid): ...


class CategoryControllerBase:
    def __init__(self): ...
    def getCategory(self): ...
    def postCategory(self): ...
    def putCategory(self): ...
    def deleteCategory(self): ...


class BrandControllerBase:
    def __init__(self): ...
    def getBrand(self): ...
    def postBrand(self): ...
    def putBrand(self): ...
    def deleteBrand(self): ...
